### ISSUE TITLE
color palette names used

### ISSUE THREAD

**Issue by PythonCoderUnicorn** [nrennie/aRt#38]
Hello nrennie ! 

Firstly, THANK YOU for this package, i love it and tried all of the starter code on the readme.

My only issue is that I was unclear what the names of the colors are from what color palette package used. I normally just use hex values. Looking into the DESCRIPTION file I see what the palettes are.

May I suggest adding the color palette libraries to your README file, so that way the end user is at least aware ?
```
library(rcartocolor)
display_carto_all()

# or 
RColorBrewer::display.brewer.all()
```

and  for the line of code in the `tile()` section `col_palette= "Veronese"`. I had no idea where this color palette came (as it is not included in the above libraries) from but Googled my way to the MetBrewer package.
```
install.packages("MetBrewer")
MetBrewer::display_all() 
```

again, thanks for such a great package.

**Comment by nrennie** [comment]
Thanks! I've added this to the README with PR #39
